@startuml
scale 1000 width

state S_Start{
S_Start --> S_Init
}

state S_Init{
S_Init --> S_Wait_For_Coins
}

state S_Wait_For_Coins{
E_In_5C --> S_5C
E_In_10C --> S_10C
E_In_20C --> S_20C
E_In_50C --> S_50C
}

state S_5C{
E_1Money_Enough --> S_Coke
E_1Money_Not_Enough --> S_Wait_For_Coins
}

state S_10C{
E_2Money_Enough --> S_Coke
E_2Money_Not_Enough --> S_Wait_For_Coins
}

state S_20C{
E_3Money_Enough --> S_Coke
E_3Money_Not_Enough --> S_Wait_For_Coins
}

state S_50C{
E_4Money_Enough --> S_Coke
E_4Money_Not_Enough --> S_Wait_For_Coins
}

state S_Coke{
S_Coke --> S_Change
}

state S_Change{
S_Change --> S_Init
}

@enduml