@startuml

node UsersComputer <<device>> {
    node "PC App" <<execution environment>>
}

node Server <<device>> {
    cloud "Webapp" <<execution environment>>
    cloud "Webserver" <<execution environment>>
}

node MobilePhone <<device>> {
    node "Application" <<execution environment>>
}

node Microcontroller <<device>> {
    node "RoombaController" <<execution environment>>
}

node Roomba <<device>>

UsersComputer <--> () HTTP
MobilePhone <--> () HTTP
Server <--> HTTP
Microcontroller <--> HTTP
Roomba <--> HTTP
Microcontroller <--> () SCI
Roomba <--> () SCI

@enduml