@startuml
namespace algorithm{
    class Timer
    abstract class roomba_algorithm
    class Clean

    Clean -|> roomba_algorithm
}

namespace systemcontrol{
    class RoombaControl
    class RoombaStateContext

    RoombaStateContext *--"1" RoombaControl
    RoombaStateContext *-"1" states.Initialise
    RoombaStateContext *-"1" states.WaitforSession
    RoombaStateContext *-"1" states.Session
    RoombaStateContext *-"1" states.Clean

    RoombaControl *-"1" io.SerialPort
}

namespace server{
    class RoombaServer
}
@enduml
