@startuml
namespace algorithm{
    class Timer
    abstract class roomba_algorithm
    class Clean
    class Spot
    class Dock

    Clean -|> roomba_algorithm
    Clean -|> Spot
    Clean -|> Dock
}

namespace systemcontrol{
    class RoombaControl
    class RoombaStateContext

    RoombaStateContext *--"1" RoombaControl
    RoombaStateContext *-"1" states.Initialise
    RoombaStateContext *-"1" states.WaitforSession
    RoombaStateContext *-"1" states.Session
    RoombaStateContext *-"1" states.Clean
    RoombaStateContext *-"1" states.ShutDown

    RoombaControl *-"1" io.SerialPort
}

namespace server{
    class RoombaServer
}
@enduml
