@startuml
[*] --> Start: init()
Start: entry / invertDirection();

Start --> Spiral_Increase
Spiral_Increase--> Spiral_Decrease: E_DONE_SPIRAL_INC
Spiral_Increase --> Start: E_HIT_OBJECT

Spiral_Decrease --> Start: E_HIT_OBJECT
Spiral_Decrease --> Stop: E_DONE_SPIRAL_DEC


@enduml