@startuml

title main statemachine

[*] --> Initialise : init()

Initialise -> WaitForMode : E_READY

WaitForMode -> Clean : E_AUTO
WaitForMode -> Session : E_SESSION

Session -> WaitForMode : E_EXIT
Session -> Clean : E_CLEAN
Session -> Spot : E_SPOT

Clean -> WaitForMode : E_STOP
Clean -> Session : E_STOP

Spot -> Session : E_STOP

@enduml