@startuml
left to right direction
skinparam packageStyle rectangle

actor user

rectangle gui {
  user -> (gui-settings)
}

rectangle website {
  user -> (web-settings)
}

rectangle controller {
  (bluetooth dongle) <-> (server)
}

rectangle roomba {
   (bluetooth dongle) ..(bluetooth module)
   user -> (on-off)
   (on-off) .> (clean) : <<extends>>
}

gui <.> server
website <.> server
@enduml