@startuml
left to right direction

skinparam packageStyle rectangle

actor wall
actor cliff
actor object
actor user
actor dockingstation

rectangle Roomba650 {
  object -- (moving)
  cliff -- (moving)
  wall -- (moving)
  ' user -- (power on)
  user -- (cleaning)
  user -- (docking)

  dockingstation -- (docking)

  (cleaning) .> (power on) : include

  (cleaning) .> (moving) : include
  (docking) .> (battery loading) : include

 ' (cleaning) .> (spot cleaning) : include

  ' (docking) .> (battery loading) : extends
}

rectangle app {
  user -- (clean)
  user -- (direction-button)
}

app <--> Roomba650
@enduml
