@startuml
left to right direction
skinparam packageStyle rectangle

actor user
actor object
actor cliff
actor dock

rectangle gui {
}

rectangle website {
}

rectangle controller {
   (bluetooth)
}

rectangle bluetoothmodule {

}

rectangle roomba {
   (sci) - bluetoothmodule
   (IR-bottom)
   (IR-front)
   (button-front)
   cliff -> (IR-bottom)
   object -> (button-front)
   dock -> (IR-front)
   user -> (on-off)
   (on-off) .> (clean) : <<extends>>
}

user <-> website
user <-> gui
(bluetooth) <.> bluetoothmodule

@enduml