@startuml
title GUI - Server: upload settings

GUI -> Server: POST /
Server -> Server: parse request
Server -> Server: check source
Server -> Server: check roomba status
Server -> Server: set roomba parameters
Server -> GUI: json

@enduml