@startuml
title GUI - Server: upload settings

GUI -> Server: POST /
Server -> RoombaController: parse request
RoombaController -> RoombaController: set roomba parameters
RoombaController -> Server: send status
Server -> GUI : json

@enduml