@startuml

==initialization==
RoombaController -> Device : setWheels()
Device -> SerialPort : write()
RoombaController -> SerialPort : readSensors()
RoombaController <-- SerialPort : sensor data

RoombaController -> Device : setRotation()
Device -> SerialPort : write()
RoombaController -> SerialPort : readSensors()
RoombaController <-- SerialPort : sensor data

@enduml