@startuml
title Website - Server: control

Browser -> Server: POST /control
Server -> RoombaController: parse request
RoombaController -> RoombaController: set roomba parameters
RoombaController -> Server: set status
Server -> Browser: json status

@enduml